spring:
  application:
    name: spring-ai-demo
  config:
    import: optional:file:.env[.properties]
  ai:
    ollama:
      chat:
        options:
          model: llama3.2
          temperature: 0.7
    openai:
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gemini-2.0-flash
        completions-path: /chat/completions
    mcp:
      client:
        stdio:
          connections:
            brave-search:
              command: npx
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}

logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai.mcp: DEBUG